//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Area_CityLandmark
    {
        public int CityLandmarkID { get; set; }
        public string CnName { get; set; }
        public string CnAbbreviation { get; set; }
        public string Big5Name { get; set; }
        public string Big5Abbreviation { get; set; }
        public string EnName { get; set; }
        public string EnAbbreviation { get; set; }
        public string PinYin { get; set; }
        public string PinYinAbbreviation { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public Nullable<short> CityLandmarkTypeID { get; set; }
        public int CityID { get; set; }
        public bool IsAvailable { get; set; }
    }
    
}
