//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.Entity
{
    public partial class Base_Holiday
    {
        public int HolidayID { get; set; }
        public string CnName { get; set; }
        public string Big5Name { get; set; }
        public string EnName { get; set; }
        public System.DateTime EffectDate { get; set; }
        public System.DateTime StarDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Description { get; set; }
        public bool IsAvailable { get; set; }
    }
    
}
