//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Flt_AirLine
    {
        public int AirLineID { get; set; }
        public string AirLineCode { get; set; }
        public string CnName { get; set; }
        public string Big5Name { get; set; }
        public string EnName { get; set; }
        public int CountryID { get; set; }
        public string Continent { get; set; }
        public bool IsAvailable { get; set; }
    }
    
}
