//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.Entity
{
    public partial class Flt_CraftType
    {
        public int CraftTypeID { get; set; }
        public string CraftTypeCode { get; set; }
        public string CNName { get; set; }
        public string Big5Name { get; set; }
        public string ENName { get; set; }
        public string Description { get; set; }
        public string WidthLevel { get; set; }
        public Nullable<int> MinSeats { get; set; }
        public Nullable<int> MaxSeats { get; set; }
        public string CraftKind { get; set; }
        public bool IsAvailable { get; set; }
    }
    
}
