//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.Entity
{
    public partial class Flt_Airport
    {
        public int AirportID { get; set; }
        public string AirportCode { get; set; }
        public string CnName { get; set; }
        public string CnAbbreviation { get; set; }
        public string Big5Name { get; set; }
        public string Big5Abbreviation { get; set; }
        public string EnName { get; set; }
        public string EnAbbreviation { get; set; }
        public int CityID { get; set; }
        public bool IsAvailable { get; set; }
    }
    
}
