//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Orders_Passenger
    {
        public int PassengerID { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string CName { get; set; }
        public string EName { get; set; }
        public string CredentialsType { get; set; }
        public string credentialsNo { get; set; }
    }
    
}
