//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Picture
    {
        public int PictureId { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string Location { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Size { get; set; }
        public string LastModifyMan { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
    
}
