//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Product_AttachPrice_Cache
    {
        public int ProductId { get; set; }
        public System.DateTime PriceDate { get; set; }
        public short CacheHour { get; set; }
        public int SectionID { get; set; }
        public short ResourceType { get; set; }
        public Nullable<short> MinQty { get; set; }
        public Nullable<int> MinSinglePrice { get; set; }
        public int MinPrice { get; set; }
        public Nullable<int> MinSinglePriceChild { get; set; }
        public Nullable<int> MinPriceChild { get; set; }
        public Nullable<short> OptionType { get; set; }
    }
    
}
