//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.Entity
{
    public partial class Product_Spec
    {
        public int SpecId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string SpecName { get; set; }
        public string SpecDesc { get; set; }
        public string Remark { get; set; }
        public Nullable<short> SeqNo { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string LastModifyMan { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public string SpecRank { get; set; }
        public string SpecType { get; set; }
        public string SpecClass { get; set; }
        public string SpecNote { get; set; }
        public Nullable<short> MinPersonNum { get; set; }
        public Nullable<short> MaxPersonNum { get; set; }
        public Nullable<short> MinGroupNum { get; set; }
    }
    
}
