//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Product_Flight
    {
        public int FlightID { get; set; }
        public int ProductId { get; set; }
        public short SeqNo { get; set; }
        public string Direction { get; set; }
        public string AirLine { get; set; }
        public string FlightNo { get; set; }
        public string FlightStyle { get; set; }
        public Nullable<short> Stops { get; set; }
        public string StopPorts { get; set; }
        public Nullable<short> TimeLength { get; set; }
        public string Dport { get; set; }
        public string Aport { get; set; }
        public Nullable<System.TimeSpan> Dtime { get; set; }
        public Nullable<System.TimeSpan> Atime { get; set; }
        public string LastModifyMan { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
    
}
