//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.Entity
{
    public partial class Product_Price_Cache
    {
        public int ProductId { get; set; }
        public System.DateTime PriceDate { get; set; }
        public short CacheHour { get; set; }
        public Nullable<int> MinBasePrice { get; set; }
        public Nullable<int> MinAttachPrice { get; set; }
        public int MinPrice { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<int> MinBasePriceChild { get; set; }
        public Nullable<int> MinAttachPriceChild { get; set; }
        public Nullable<int> MinPriceChild { get; set; }
        public Nullable<short> MinPersonNum { get; set; }
    }
    
}
