//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.Entity
{
    public partial class Product_Schedule_Detail
    {
        public int ScheduleDetailId { get; set; }
        public int ProductId { get; set; }
        public int ScheduleId { get; set; }
        public string ScheduleType { get; set; }
        public string TakeOffTime { get; set; }
        public string Description { get; set; }
        public string LastModifyMan { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
    
}
