//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Property
    {
        public int PropertyId { get; set; }
        public string PropertyNo { get; set; }
        public string PropertyName { get; set; }
        public string PropertyCName { get; set; }
        public string PropertyEName { get; set; }
        public string Pinyin { get; set; }
        public string PinyinAbb { get; set; }
        public string ENameAbb { get; set; }
        public string PropertyPath { get; set; }
        public string ParentPropertyPath { get; set; }
        public Nullable<short> PropertyLevel { get; set; }
        public Nullable<short> SeqNo { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<short> Company { get; set; }
        public string LastModifyMan { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
    
}
