
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HHTravel.DataAccess.HardCode
{
    /// <summary>
    /// 对应PROPERTY表中定义的父级属性路径
    /// 在此提供对应关系，是为了增强代码可读性以及引入强类型检查
    /// </summary>
    public enum PropertyPath
    {
        /// <summary>
        /// 2	线路类型
        /// </summary>
        线路类型 = 2,
        /// <summary>
        /// 3	资源类型
        /// </summary>
        资源类型 = 3,
        /// <summary>
        /// 4	产品主题
        /// </summary>
        产品主题 = 4,
        /// <summary>
        /// 5	一级目的地
        /// </summary>
        一级目的地 = 5,
        /// <summary>
        /// 6	二级目的地
        /// </summary>
        二级目的地 = 6,
        /// <summary>
        /// 7	出发城市
        /// </summary>
        出发城市 = 7,
        /// <summary>
        /// 8	日程类型
        /// </summary>
        日程类型 = 8,
        /// <summary>
        /// 9	信息类型
        /// </summary>
        信息类型 = 9,
        /// <summary>
        /// 10	对象类型
        /// </summary>
        对象类型 = 10,
        /// <summary>
        /// 11	图片位置
        /// </summary>
        图片位置 = 11,
        /// <summary>
        /// 12	子产品选择方式
        /// </summary>
        子产品选择方式 = 12,
        /// <summary>
        /// 13	语言类别
        /// </summary>
        语言类别 = 13,
        /// <summary>
        /// 14	出发年月
        /// </summary>
        出发年月 = 14,
        /// <summary>
        /// 17	酒店信息
        /// </summary>
        酒店信息 = 17,
        /// <summary>
        /// 21	网站栏目
        /// </summary>
        网站栏目 = 21,
        /// <summary>
        /// 1	产品类型
        /// </summary>
        产品类型 = 1,
        /// <summary>
        /// 22	线路子类
        /// </summary>
        线路子类 = 22,
    }
}