//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using HHTravel.Entity;
using System;

namespace HHTravel.DataAccess.DbContexts
{
    public partial class CustomerDbEntities : DbEntitiesBase, IDisposable
    {
        internal CustomerDbEntities()
            : base("name=CustomerDbEntities")
        {
        }
    
        internal CustomerDbEntities(string connectionString) : base(connectionString)
    	{
    	
    	}
    
    	internal CustomerDbEntities(DbConnection existingConnection, bool contextOwnsConnection)
                : base(existingConnection, contextOwnsConnection)
        {
        }
    
        public DbSet<Customer> Customer { get; set; }
        public DbSet<SubNews> SubNews { get; set; }
        public DbSet<Mkt_Html> Mkt_Html { get; set; }
    }
}
