//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HHTravel.CRM.Booking_Online.DataAccess.HardCode
{
    /// <summary>
    /// 对应PROPERTYTYPE表中定义的常量
    /// 在此提供对应关系，一是为了增强代码可读性；
    /// 后续还可以考虑采用代码自动生成
    /// </summary>
    internal enum PropertyPath
    {
        /// <summary>
        /// 1	产品类型
        /// </summary>
        产品类型 = 1,
        /// <summary>
        /// 2	线路类型
        /// </summary>
        线路类型 = 2,
        /// <summary>
        /// 3	资源类型
        /// </summary>
        资源类型 = 3,
        /// <summary>
        /// 4	产品主题
        /// </summary>
        产品主题 = 4,
        /// <summary>
        /// 5	一级目的地
        /// </summary>
        一级目的地 = 5,
        /// <summary>
        /// 6	二级目的地
        /// </summary>
        二级目的地 = 6,
        /// <summary>
        /// 7	出发城市
        /// </summary>
        出发城市 = 7,
        /// <summary>
        /// 8	日程类型
        /// </summary>
        日程类型 = 8,
        /// <summary>
        /// 9	信息类型
        /// </summary>
        信息类型 = 9,
        /// <summary>
        /// 10	对象类型
        /// </summary>
        对象类型 = 10,
        /// <summary>
        /// 11	图片位置
        /// </summary>
        图片位置 = 11,
        /// <summary>
        /// 12	子产品选择方式
        /// </summary>
        子产品选择方式 = 12,
        /// <summary>
        /// 13	语言类别
        /// </summary>
        语言类别 = 13,
        /// <summary>
        /// 14	出发月份
        /// </summary>
        出发月份 = 14,
        /// <summary>
        /// 15	品牌理念
        /// </summary>
        品牌理念 = 15,
        /// <summary>
        /// 16	热门品鉴
        /// </summary>
        热门品鉴 = 16,
        /// <summary>
        /// 5	行程大图
        /// </summary>
        行程大图 = 5,
        /// <summary>
        /// 6	酒店大图
        /// </summary>
        酒店大图 = 6,
        /// <summary>
        /// 17	酒店信息
        /// </summary>
        酒店信息 = 17,
    }
}