//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using HHTravel.CRM.Booking_Online.Entity;

namespace HHTravel.CRM.Booking_Online.DataAccess.DbContexts
{
    public partial class CustomerDbEntities : DbEntitiesBase
    {
        public CustomerDbEntities()
            : base("name=CustomerDbEntities")
        {
        }
    
        public CustomerDbEntities(string connectionString) : base(connectionString)
    	{
    	
    	}
    
    	public CustomerDbEntities(DbConnection existingConnection, bool contextOwnsConnection)
                : base(existingConnection, contextOwnsConnection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customer { get; set; }
        public DbSet<SubNews> SubNews { get; set; }
    }
}
