//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.IO;
using EFCachingProvider;
using EFCachingProvider.Caching;
using EFProviderWrapperToolkit;
using EFTracingProvider;
using HHTravel.CRM.Booking_Online.Entity;

namespace HHTravel.CRM.Booking_Online.DataAccess.DbContexts
{
    public partial class GovDbEntities : DbEntitiesBase
    {
        internal GovDbEntities()
            : base("name=GovDbEntities")
        {
        }
    
        internal GovDbEntities(string connectionString) : base(connectionString)
    	{
    	
    	}
    
    	internal GovDbEntities(DbConnection existingConnection, bool contextOwnsConnection)
                : base(existingConnection, contextOwnsConnection)
        {
        }
    
        public DbSet<Email> Email { get; set; }
    }
}
