//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using HHTravel.CRM.Booking_Online.Entity;

namespace HHTravel.CRM.Booking_Online.DataAccess.DbContexts
{
    public partial class ProductDbEntities : DbEntitiesBase
    {
    	public ProductDbEntities() : base("name=ProductDbEntities")
    	{
    	
    	}
    
        public ProductDbEntities(string connectionString) : base(connectionString)
    	{
    	
    	}
    
    	public ProductDbEntities(DbConnection existingConnection, bool contextOwnsConnection)
                : base(existingConnection, contextOwnsConnection)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area_City> Area_City { get; set; }
        public DbSet<Area_CityLandmark> Area_CityLandmark { get; set; }
        public DbSet<Area_Continent> Area_Continent { get; set; }
        public DbSet<Area_Country> Area_Country { get; set; }
        public DbSet<Area_Province> Area_Province { get; set; }
        public DbSet<Base_Holiday> Base_Holiday { get; set; }
        public DbSet<Base_IDcardType> Base_IDcardType { get; set; }
        public DbSet<Base_IP> Base_IP { get; set; }
        public DbSet<Base_MPCode> Base_MPCode { get; set; }
        public DbSet<Base_ZipCode> Base_ZipCode { get; set; }
        public DbSet<Fin_Bank> Fin_Bank { get; set; }
        public DbSet<Fin_CurrencyISO> Fin_CurrencyISO { get; set; }
        public DbSet<Flt_AirLine> Flt_AirLine { get; set; }
        public DbSet<Flt_Airport> Flt_Airport { get; set; }
        public DbSet<Flt_CraftType> Flt_CraftType { get; set; }
        public DbSet<Picture> Picture { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<Product_Flight> Product_Flight { get; set; }
        public DbSet<Product_Info> Product_Info { get; set; }
        public DbSet<Product_NoDeparture> Product_NoDeparture { get; set; }
        public DbSet<Product_Price> Product_Price { get; set; }
        public DbSet<Product_Property> Product_Property { get; set; }
        public DbSet<Product_Schedule> Product_Schedule { get; set; }
        public DbSet<Product_Schedule_Detail> Product_Schedule_Detail { get; set; }
        public DbSet<Product_Section> Product_Section { get; set; }
        public DbSet<Product_Spec> Product_Spec { get; set; }
        public DbSet<Product_Stock> Product_Stock { get; set; }
        public DbSet<Property> Property { get; set; }
        public DbSet<SEO> SEO { get; set; }
        public DbSet<Product_Attach_Product> Product_Attach_Product { get; set; }
    }
}
