
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HHTravel.CRM.Booking_Online.Infrastructure.Crosscutting
{
    /// <summary>
    /// 对应PROPERTY表中定义的父级属性路径为“网站栏目”的属性
    /// 在此提供对应关系，是为了增强代码可读性以及引入强类型检查
    /// </summary>
    public enum SiteColumn
    {
        /// <summary>
        /// 1	品牌理念
        /// </summary>
        品牌理念 = 1,
        /// <summary>
        /// 5	热门品鉴
        /// </summary>
        热门品鉴 = 5,
        /// <summary>
        /// 7	电子报订阅
        /// </summary>
        电子报订阅 = 7,
        /// <summary>
        /// 6	隐私政策
        /// </summary>
        隐私政策 = 6,
        /// <summary>
        /// 8	联络我们
        /// </summary>
        联络我们 = 8,
        /// <summary>
        /// 2	目的地
        /// </summary>
        目的地 = 2,
        /// <summary>
        /// 3	旅行主题
        /// </summary>
        旅行主题 = 3,
        /// <summary>
        /// 4	出发月份
        /// </summary>
        出发月份 = 4,
        /// <summary>
        /// 9	全站首页
        /// </summary>
        全站首页 = 9,
        /// <summary>
        /// 10	简体首页
        /// </summary>
        简体首页 = 10,
        /// <summary>
        /// 11	环游世界栏目
        /// </summary>
        环游世界栏目 = 11,
        /// <summary>
        /// 12	网站地图栏目
        /// </summary>
        网站地图栏目 = 12,
        /// <summary>
        /// 13	友情链接
        /// </summary>
        友情链接 = 13,
        /// <summary>
        /// 14	合作专区
        /// </summary>
        合作专区 = 14,
    }
}