//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Base_IP
    {
        public int IPID { get; set; }
        public string StartIP { get; set; }
        public string EndIP { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    }
    
}
