//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Base_MPCode
    {
        public int MPCodeID { get; set; }
        public string Prefix7 { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Cityname { get; set; }
        public string MPType { get; set; }
    }
    
}
