//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Fin_CurrencyISO
    {
        public int CurrencyISOID { get; set; }
        public string Country { get; set; }
        public string CurrencyISO { get; set; }
        public string CurrencySymbol { get; set; }
        public string CnName { get; set; }
        public string Big5Name { get; set; }
        public string EnName { get; set; }
        public bool IsAvailable { get; set; }
    }
    
}
