//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class Product_Price
    {
        public int PriceId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> SpecId { get; set; }
        public System.DateTime EffectDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public int Price { get; set; }
        public Nullable<int> PriceStay { get; set; }
        public Nullable<int> PriceMarketing { get; set; }
        public Nullable<int> PriceChild { get; set; }
        public Nullable<int> PriceStayChild { get; set; }
        public Nullable<int> PriceBaby { get; set; }
        public Nullable<int> PriceStayBaby { get; set; }
        public string LastModifyMan { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
    
}
