//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace HHTravel.CRM.Booking_Online.Entity
{
    public partial class SubNews
    {
        public int SubId { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
    
}
